version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_container.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user
