version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose push

      - sed -i -e "s|LOGIN_COMMAND|$(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)|g" scripts/after_install.sh

      - sed -i -e "s|AWS_DEFAULT_REGION_ENV|$AWS_DEFAULT_REGION|g" scripts/start_container.sh
      - sed -i -e "s|AWS_ACCOUNT_ID_ENV|$AWS_ACCOUNT_ID|g" scripts/start_container.sh

artifacts:
  type: zip
  files:
    - 'docker-compose.yml'
    - 'nginx/default.conf'
    - 'appspec.yml'
    - 'scripts/after_install.sh'
    - 'scripts/start_container.sh'
    - 'scripts/kill_container.sh'
