version: "3"

services:
  app:
    build: .
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/api-star:latest
    container_name: apistar-gunicorn
    restart: always
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.13
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
